### ISSUE TITLE
Civi revision approval flow

### ISSUE THREAD

**Issue by brylie** [CiviWikiorg/CiviWiki#40]
*Placeholder issue, edit as needed*

# User story

> As a civi author
> I would like to allow other members to suggest edits to my civis
> so I can approve edits and collaborate with other community members

# Goal
Create a workflow that would allow civis to be edited by multiple persons. The workflow should have a primary 'editor', who is responsible for approving changes.

**Comment by brylie** [comment]
For the most part, the content revision tools available in the Django ecosystem are designed for a linear content editing process, meaning each content revision happens in a strict sequence.

However, this user story implies an approval process, which may take some amount of time. During the review process, it may be possible for other CiviWiki members to suggest changes to the same Civi. Since there is a possibility of concurrent edits, a linear revision plugin does not seem sufficient. 

It may be worth consideration to use a version control system, such as Git, with flat Markdown files as a persistence and revision layer for Civis.

**Comment by CiviWiki** [comment]
I think we should aim to keep this system as simple and user friendly as possible. I wish we could go with a traditional wiki editing system, but the political nature of this discussion, and the value of civies with lots of positive votes creates significant risk of griefing. 

My thought was that a markdown system similar to track changes, with the power to administer who can suggest edits (i.e. all users, all users minus blocker users, all followers, all followers minus blocked followers, only select users, no editing) would give the community tools to collaborate and manage the edits on a single version of the Civi (similar to a wiki entry). 

All this said, lets start on the bill integration first and perhaps set up a group video chat to discuss this feature before we begin in ernest.

**Comment by brylie** [comment]
Sounds good.

**Comment by brylie** [comment]
Migrated issue> https://github.com/CiviWiki/OpenCiviWiki/issues/5
