### ISSUE TITLE
Installation instructions for new developers

### ISSUE THREAD

**Issue by brylie** [CiviWikiorg/CiviWiki#41]
# User Story
> As a new contributor
> I would like explicit instructions about how to set up a development environment
> so that I can quickly start improving CiviWiki

# Goal
Add installation/setup instructions to the repository root, to help new developers get started quickly.

**Comment by CiviWiki** [comment]
I really like this idea, and want to move towards being more open to contributions. We should reassess this after the UI redesign is complete and we have bills integrated.

**Comment by brylie** [comment]
It is worth noting that a [pull-request is already open](https://github.com/CiviWikiorg/CiviWiki/issues/42) with installation instructions. I basically made notes while feeling my way through the initial development environment setup.
