### ISSUE TITLE
Ignore static files

### ISSUE THREAD

**Issue by brylie** [CiviWikiorg/CiviWiki#46]
Git is trying to track changes to the **staticfiles** directory. Add **staticfiles** to `.gitignore`, so Git will not track the default staticfiles directory.

**Comment by JOO33** [comment]
local/non-production development previously has been done with the django setting DEBUG = TRUE (although it wasn't indicated anywhere) which never spawned the creation of staticfiles/ . I don't see it hurting anything to add this, but perhaps we can add a bit about using the DEBUG variable in contrib, or change settings.py to adjust accordingly.

**Comment by brylie** [comment]
Migrated issue: https://github.com/CiviWiki/OpenCiviWiki/issues/6
