### ISSUE TITLE
For consistency of URLs, enable the APPEND_SLASH setting

### ISSUE THREAD

**Issue by brylie** [CiviWikiorg/CiviWiki#49]
When trying to access `http://localhost:8000/admin`, I get an error

> Page Does not exist! 

Determine how to consistently handle trailing slashes.

# Resources
Django has an [APPEND_SLASH](https://docs.djangoproject.com/en/dev/ref/settings/#append-slash) setting for this type of scenario.

**Comment by JOO33** [comment]
This is from some of the initial developers using a trailing slash mandatory for some pages while some others did not. Would the optional slash notation in the url regex handle this the same as well? Meanwhile, Most of the pages do have a trailing slash. Also, django admin has not been incorporated within our project

**Comment by brylie** [comment]
Using the `APPEND_SLASH=True` would improve **consistency**.

> Also, django admin has not been incorporated within our project

It seems like [Django admin is enabled](https://github.com/CiviWikiorg/CiviWiki/blob/dev/civiwiki/settings.py#L40) and the [admin routes are configured](https://github.com/CiviWikiorg/CiviWiki/blob/dev/civiwiki/urls.py#L26).

**Comment by JOO33** [comment]
You are correct, my confusion came from the same exact slash issue. Regarding APPEND_SLASH, I've tried to set that in settings.py in the past with no avail. My understanding was that you needed to set the variable to True and make sure to include the CommonMiddleware. but seemed like it wasn't working. Any ideas?

**Comment by brylie** [comment]
Hm. I will give it a try and open a PR if things work :-)

**Comment by brylie** [comment]
I see that the [CommonMiddleware is enabled](https://github.com/CiviWikiorg/CiviWiki/blob/dev/civiwiki/settings.py#L59), and that `APPEND_SLASH` should be `True` by default. 

How does Django route to the **Page Does not exist** view? Perhaps that is where the problem is?

**Comment by CiviWiki** [comment]
Has this problem been fixed? Label as resolved if so.

**Comment by brylie** [comment]
It is not yet resolved. I suspect that it is related to our route definition for handling missing pages. I.e. the 'Page does not exist' route may be catching requests before the CommonMiddleware can append the trailing slash.

**Comment by brylie** [comment]
PR #67 is open, which restores Django default 404 handling and uses the same 404 view.

**Comment by brylie** [comment]
Ping @jl24 PR is ready for review.
