### ISSUE TITLE
How to allow initial user to access 'beta' features in local development environment?

### ISSUE THREAD

**Issue by brylie** [CiviWikiorg/CiviWiki#50]
I have managed to get CiviWiki running locally, created an initial superuser, and created a CiviWiki user with all permissions. However, I keep getting the "Sorry, we are still in development" page after logging in.

![screenshot_20170714_202838](https://user-images.githubusercontent.com/17307/28223172-080b5ef0-68d3-11e7-8b53-7d7e4a401481.png)

How can I allow the new user to access CiviWiki properly?

**Comment by brylie** [comment]
Related issue #48

**Comment by JOO33** [comment]
same as #48 use a db client for now and set beta_access under api_account to True

**Comment by CiviWiki** [comment]
Note: We are also looking to cut the beta blocker soon to open up the project to more users
