### ISSUE TITLE
Consider removing dependency on Google Maps?

### ISSUE THREAD

**Issue by brylie** [CiviWikiorg/CiviWiki#51]
The Google Maps dependency may be unnecessary, and poses an additional encumbrance when setting up a development environment. For example, without a Google Maps API key, the new user registration wizard cannot be completed:

![screenshot_20170714_204541](https://user-images.githubusercontent.com/17307/28223790-68aa8cac-68d5-11e7-8394-0180b680d470.png)

Consider the reasons for using Google Maps as a base map provider, and whether those needs could be met with an Open Source project such as [Leaflet](http://leafletjs.com/) + [OpenStreetMap](https://www.openstreetmap.org/#map=15/52.5137/13.3515).

**Comment by CiviWiki** [comment]
Are there any open source alternatives we could integrate without too much work?

**Comment by brylie** [comment]
The combination of Leaflet and OpenStreetMap might be a good alternative. We can estimate the work if/when this becomes higher priority.

**Comment by brylie** [comment]
Migrated issue: https://github.com/CiviWiki/OpenCiviWiki/issues/7
