### ISSUE TITLE
How to populate initial categories, so users can create threads?

### ISSUE THREAD

**Issue by brylie** [CiviWikiorg/CiviWiki#52]
After logging in with an initial user, on a fresh CiviWiki installation, there is a button to 'create thread'. On the 'create thread' screen, there is a drop-down to select a category. However, there are no existing categories on a fresh installation and no apparent way to create any categories.

How can I create categories for threads on a fresh CiviWiki installation.

Also, lets consider registering categories with the admin section, since it would be useful for new admins to manage the CiviWiki deployment.

**Comment by JOO33** [comment]
There are two datasets that should be loaded to properly initialize the app which are both under /data you can use the python manage.py loaddata command to load both congress.json and categories.json

**Comment by brylie** [comment]
OK, I've done that and added it to the CONTRIBUTING.md in PR #42
