### ISSUE TITLE
Fix CSRF middleware

### ISSUE THREAD

**Issue by brylie** [CiviWikiorg/CiviWiki#53]
There is a [TODO in `settings.py` to 'fix the CSRF middleware'](https://github.com/CiviWikiorg/CiviWiki/blob/dev/civiwiki/settings.py#L60). This issue is a placeholder to make sure we resolve the issue with CSRF middleware.

What is the issue that prevents us from using CSRF?

**Comment by JOO33** [comment]
It was just a frontend setup issue. I have recently fixed it on my local branch so that should be pushed up pretty soon.

**Comment by brylie** [comment]
OK, please reference this issue from your PR description. E.g. 'Closes #53'

**Comment by brylie** [comment]
If this is resolved, it should probably be closed. Was this resolved with a pull request?

**Comment by brylie** [comment]
Migrated issue: https://github.com/CiviWiki/OpenCiviWiki/issues/8
