### ISSUE TITLE
Dismiss 'New Thread' modal on success

### ISSUE THREAD

**Issue by brylie** [CiviWikiorg/CiviWiki#55]
Currently, there is a delay when creating a new thread. The 'thread created' message appears, but the modal is still open.

![peek 2017-07-14 21-25](https://user-images.githubusercontent.com/17307/28225374-1d741cde-68db-11e7-9b11-d434125eafbe.gif)

Determine how to optimize the flow when users create new threads, so they receive immediate feedback on success. I.e. the modal might close at the same time the success message displays (while triggering redirect is in progress).

**Comment by CiviWiki** [comment]
This feature should be simplified into  a title, category and location which automatically opens into the newly formed thread (rather than the background page)

**Comment by brylie** [comment]
Migrated issue: https://github.com/CiviWiki/OpenCiviWiki/issues/10
