### ISSUE TITLE
Civi 'temp score' display has unnecessary precision

### ISSUE THREAD

**Issue by brylie** [CiviWikiorg/CiviWiki#57]
The 'temp score' display on a Civi card has over ten significant digits of precision.

![screenshot_20170714_213539](https://user-images.githubusercontent.com/17307/28225976-181da73a-68dd-11e7-92a8-4c32f47bddce.png)

# Goal
Consider rounding or truncating the 'temp score' display to improve readability.

**Comment by CiviWiki** [comment]
Good call, that is something we need to fix for optimization! But its not a high priority. On Trello we can give cards priority, is there any similar functionality with Github issues?

**Comment by brylie** [comment]
We could look at a Kanban display for Github issues, such as Waffle.io or Zenhub. That way we could keep a growing backlog while still being able to prioritize issues through 'the bottleneck'.

**Comment by brylie** [comment]
Migrated issue: https://github.com/CiviWiki/OpenCiviWiki/issues/12
