### ISSUE TITLE
Create labels for issue prioritization

### ISSUE THREAD

**Issue by brylie** [CiviWikiorg/CiviWiki#58]
Note: this is a project management issue.

Some issues will have higher priority than others, and we need a way to prioritize our work.

# User story
> As a product owner
> I need to indicate priority of project issues
> so I can plan the project roadmap

# Goal
Have a method to prioritize Github issues.

# Suggestion
Use labels for issue priority. E.g.
- priority: high
- priority: low

**Comment by CiviWiki** [comment]
I have added a few new labels and want input on how to integrate them into our work flow. 

With the current labels, we can assign issues, mark as three levels of priority and resolve issues. 

Please comment with any additional label suggestions or policies for utilizing them more effectively .

**Comment by brylie** [comment]
Closing issue, since it is resolved.
