### ISSUE TITLE
Transfer repo to 'CiviWiki.org' organization

### ISSUE THREAD

**Issue by brylie** [CiviWikiorg/CiviWiki#59]
Now that we have an organization for collaboration, lets transfer this repository to that organization. Transferring the repo will include all of the code as well as issues.

**Comment by mdwest** [comment]
@jl24 can we make this transfer with our current admin powers. I contacted github and should be able to get admin control back, but if we are moving to the new org do we need to?

**Comment by JOO33** [comment]
I would prefer to not leave our repository with a github organization that we have no control over. We should move our repository to the new org. Just need to make sure that we correct the auto deployment urls for our servers when we do so.

**Comment by mdwest** [comment]
I agree and I prefer to use the civiwiki name anyway.  What steps do we
need to take to do this?

**Comment by brylie** [comment]
Basically,

1. create a new organization
2. make sure your account (mdwest) is an owner of the new organization
3. under settings for this repository, click 'transfer ownership'
