### ISSUE TITLE
Integrate OpenStates and Pro-Publica Congress APIs

### ISSUE THREAD

**Issue by brylie** [CiviWikiorg/CiviWiki#60]
# Goals
1. Integrate [OpenStates API](http://docs.openstates.org/en/latest/api/) and [Pro-Publica Congress API](https://www.propublica.org/datastore/api/propublica-congress-api) into CiviWiki allowing: 
    - Attachment of bills to Solution Civies 
    - Local viewing of Bill information for attached bills (Bill summary, Bill Text, Bill status) 
    - Tracking of Representatives Voting on Attached Bills 
2. Develop a basic, but expandable, algorithm to compare the percentage of time any representatives’ voting on attached bills aligns with any any constituent users’ subset of supported/opposed bills.

# Minimum Features
- Autocomplete search form to search and attach bill if the user knows the title or bill number
    - Automatically saving all active bill titles (and historical bills in case someone supports a previously defeated bill) to local database. 
- Link to key information of any legislation attached to a Civi (Opened in new window) 
    - Possibly saving this information to our database for any legislation attached to a Civi. 
- Percentage ratio of agreement with Representatives displayed on account page
- Progress of bills listed on My issues (in committee, first reading, second reading, third reading, passed/defeated, signed by executive) 
- Number of users supporting/opposing bills (Nationally, by state, by district) 
    - To be used on representative pages by our lead developer

# Design Considerations 
- We will advise users to complete bill research using existing services such as billtrack50.com. Accordingly, this system only needs to link all bills, track attached bills and allow users to quickly reference key information about attached bills 
- Minimize the amount of information we need to store on our servers while ensuring stable access to essential legislative information.

**Comment by brylie** [comment]
I am thinking that we want to call third-party APIs from server-side code, while the Client just calls a CiviWiki API endpoint (perhaps opening a channel):

![screenshot_20170805_104548](https://user-images.githubusercontent.com/17307/28993964-5f6c7798-79cb-11e7-81e4-c27a7d5e9314.png)

```
https://bramp.github.io/js-sequence-diagrams/
Title: Third-party API integration

Client->Server: (1) call internal API
Server->API: (2) make authenticated request
API->Server: (3) Return data
Server->Client: (4) relay data

Note right of Client: Channel
Note right of Server: REST
```

@jl24 does this approach seem corret and/or consistent with other parts of CiviWiki? What are some examples of code in the CiviWiki project, or elsewhere, that I might follow as a design pattern?

**Comment by mdwest** [comment]
Unless Joohee has any objections I approve this schema.

**Comment by brylie** [comment]
I would also like to use Django REST Framework (DRF) for the API endpoint that would relay the third party data. DRF will give us a lot of structure and tools for building proper API endpoints, and there is already a note about porting CiviWiki APIs to DRF #74 

@jl24 do you have any thoughts or feedback?

**Comment by brylie** [comment]
Today, I have a working API endpoint, using DRF. The endpoint allows a query string to be submitted to the Open States API, and relays the data back to the client. If no `query` string is provided, the endpoint returns a 400 error response.

**Comment by brylie** [comment]
Migrated issue: https://github.com/CiviWiki/OpenCiviWiki/issues/13
