### ISSUE TITLE
Adopt community code of conduct

### ISSUE THREAD

**Issue by brylie** [CiviWikiorg/CiviWiki#61]
In order to set a good foundation for community building, we can adopt a code of conduct. We don't have to spend a lot of time inventing a code of conduct, and can simply adopt an existing one that we agree with.

# Resources
- OpenSource Guide [Code of Conduct](https://opensource.guide/code-of-conduct/)
- Producing Open Source Software - Setting the Tone: [Code of Conduct](http://producingoss.com/en/setting-tone.html#code-of-conduct)
- Github help: [Adding a code of conduct to your project](https://help.github.com/articles/adding-a-code-of-conduct-to-your-project/)

**Comment by mdwest** [comment]
Based on a preliminary review of the resources you attached I believe the latest version of the contributor-covenant would work for our project. 

If so should this be a separate document or incorporated into our community guidelines? 

http://contributor-covenant.org/version/1/4/

**Comment by brylie** [comment]
Jep. GitHub recommends including the code of conduct in the project root in a file named *CODE_OF_CONDUCT.md*

**Comment by brylie** [comment]
Migrated: https://github.com/CiviWiki/OpenCiviWiki/issues/14
