### ISSUE TITLE
Decide on project versioning scheme

### ISSUE THREAD

**Issue by brylie** [CiviWikiorg/CiviWiki#63]
As a software project, we should release periodic versions. To release sequential versions, we need to decide on a versioning scheme.

# Resources
- [Semantic Versioning](http://semver.org/)
- [PEP 396 -- Module Version Numbers](https://www.python.org/dev/peps/pep-0396/)
- [PEP 440 -- Version Identification and Dependency Specification](https://www.python.org/dev/peps/pep-0440/)

**Comment by mdwest** [comment]
The Semantic Versioning system is my preference unless one of the other schemes have significant benefits for open source development.

**Comment by brylie** [comment]
One caveat is that semantic versioning seems to be good for small libraries that are integrated into larger systems. Developers of larger applications need to know about breaking changes in their libraries/frameworks. For a project at the level of CiviWiki, indicating backwards incompatibility might not be as important (unless we are signaling that changes are incompatible with existing deployments).

**Comment by brylie** [comment]
Migrated: https://github.com/CiviWiki/OpenCiviWiki/issues/15
