### ISSUE TITLE
Make initial project release

### ISSUE THREAD

**Issue by brylie** [CiviWikiorg/CiviWiki#64]
Although this project has been under development for some time, it is not too late to make an official, initial release. Once we have determined a project versioning scheme, make an official release on GitHub.

**Comment by mdwest** [comment]
I really like this idea. As soon as Joohee has completed the redesigns we discussed after our testing event, we should return to this and make a release.

**Comment by brylie** [comment]
Migrated: https://github.com/CiviWiki/OpenCiviWiki/issues/16
