### ISSUE TITLE
Update project to use Python 3

### ISSUE THREAD

**Issue by brylie** [CiviWikiorg/CiviWiki#66]
CiviWiki seems to depend on Python 2.7. What are some of the reasons for staying with 2.7?

# Goal
Support the latest features of Python, such as `async` / `await`, by updating CiviWiki source/dependencies to support Python 3.

**Comment by JOO33** [comment]
There's no good reason and changing the python version to 3 just has not been a priority. I would also prefer if we move to Python 3 when we can.

**Comment by brylie** [comment]
Migrated: https://github.com/CiviWiki/OpenCiviWiki/issues/18
