### ISSUE TITLE
Clean up merged/stale branches

### ISSUE THREAD

**Issue by brylie** [CiviWikiorg/CiviWiki#72]
There are several branches in this GitHub repository that have been merged or might be stale. Consider deleting merged branches, since they are now part of the main-line, and getting rid of stale branches too.

# Goal
Remove old branches for a cleaner development environment.

**Comment by JOO33** [comment]
note: dev, staging, and master are necessary main branches. anything prefixed with feature/ is current and should kept. Everything else can be pruned out.

**Comment by brylie** [comment]
Migrated: https://github.com/CiviWiki/OpenCiviWiki/issues/22
