### ISSUE TITLE
Test project with Django 1.11.x

### ISSUE THREAD

**Issue by brylie** [CiviWikiorg/CiviWiki#73]
Django 1.11 is the latest Long Term Support (LTS) release. Test the project with Django 1.11 and upgrade if possible.

# Goal
Upgrade project to latest Django LTS release.

**Comment by mdwest** [comment]
I believe joohee is working on this. @jl24 can you push your latest code and touch base with Brylie on this.

**Comment by brylie** [comment]
Migrated: https://github.com/CiviWiki/OpenCiviWiki/issues/23
